# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-06 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obs_department', '0001_initial'),
        ('obs_semester', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept_date', models.CharField(max_length=15)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obs_department.Department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obs_semester.Semester')),
            ],
            options={
                'verbose_name_plural': 'Eğitim Planları',
                'verbose_name': 'Eğitim Planı',
            },
        ),
    ]
