# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-04 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=50)),
                ('faculty_code', models.CharField(max_length=20)),
                ('faculty_address', models.CharField(max_length=220)),
                ('faculty_tel', models.CharField(max_length=12)),
                ('faculty_fax', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name_plural': 'Fakülteler',
                'verbose_name': 'Fakülte',
            },
        ),
    ]
