# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-16 14:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('obs_student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default=datetime.datetime(2016, 11, 16, 14, 16, 2, 685914, tzinfo=utc), upload_to='students'),
            preserve_default=False,
        ),
    ]
