# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-06 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obs_register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid_exam', models.IntegerField()),
                ('final_exam', models.IntegerField()),
                ('make_up_exam', models.IntegerField()),
                ('make_up_exam_status', models.BooleanField(default=False)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obs_register.Register')),
            ],
            options={
                'verbose_name': 'Seçilen Dersin Notu',
                'verbose_name_plural': 'Seçilen Derslerin Notlari',
            },
        ),
    ]
