# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-06 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obs_register_note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registernote',
            name='make_up_exam',
            field=models.IntegerField(null=True),
        ),
    ]
