# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-06 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obs_register_note', '0002_auto_20161106_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registernote',
            name='register',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='obs_register.Register'),
        ),
    ]
