# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-06 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obs_lecturer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=15)),
                ('c_type', models.CharField(max_length=15)),
                ('credit', models.IntegerField()),
                ('ects', models.IntegerField()),
                ('lab_hour', models.IntegerField()),
                ('course_hour', models.IntegerField()),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obs_lecturer.Lecturer')),
            ],
            options={
                'verbose_name': 'Ders',
                'verbose_name_plural': 'Dersler',
            },
        ),
    ]
