# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-06 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('elective_credits', models.IntegerField()),
                ('compulsory_credits', models.IntegerField()),
                ('course_amount', models.IntegerField()),
                ('total_elective_amount', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Dönem',
                'verbose_name_plural': 'Dönemler',
            },
        ),
    ]
