# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-06 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obs_course', '0002_auto_20161106_1444'),
        ('obs_semester', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferedCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obs_course.Course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obs_semester.Semester')),
            ],
            options={
                'verbose_name_plural': 'Açılan Dersler',
                'verbose_name': 'Açılan Ders',
            },
        ),
    ]
